# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: upload.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='upload.proto',
  package='',
  syntax='proto3',
  serialized_pb=_b('\n\x0cupload.proto\"1\n\x05Tdata\x12\x0c\n\x04\x64\x61ta\x18\x01 \x01(\t\x12\x0c\n\x04size\x18\x02 \x01(\x03\x12\x0c\n\x04name\x18\x03 \x01(\t2(\n\x06Upload\x12\x1e\n\x06\x46ileup\x12\x06.Tdata\x1a\x06.Tdata\"\x00(\x01\x30\x01\x62\x06proto3')
)




_TDATA = _descriptor.Descriptor(
  name='Tdata',
  full_name='Tdata',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='data', full_name='Tdata.data', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='size', full_name='Tdata.size', index=1,
      number=2, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='name', full_name='Tdata.name', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=16,
  serialized_end=65,
)

DESCRIPTOR.message_types_by_name['Tdata'] = _TDATA
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Tdata = _reflection.GeneratedProtocolMessageType('Tdata', (_message.Message,), dict(
  DESCRIPTOR = _TDATA,
  __module__ = 'upload_pb2'
  # @@protoc_insertion_point(class_scope:Tdata)
  ))
_sym_db.RegisterMessage(Tdata)



_UPLOAD = _descriptor.ServiceDescriptor(
  name='Upload',
  full_name='Upload',
  file=DESCRIPTOR,
  index=0,
  options=None,
  serialized_start=67,
  serialized_end=107,
  methods=[
  _descriptor.MethodDescriptor(
    name='Fileup',
    full_name='Upload.Fileup',
    index=0,
    containing_service=None,
    input_type=_TDATA,
    output_type=_TDATA,
    options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_UPLOAD)

DESCRIPTOR.services_by_name['Upload'] = _UPLOAD

# @@protoc_insertion_point(module_scope)
